# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        bj_db_provider:
            entity:
                class:    BJ\UserBundle\Entity\User
                property: username

    encoders:
        BJ\UserBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

            guard:
                authenticators:
                    - bj.form_authenticator
                entry_point: bj.form_authenticator

            form_login:
                login_path:           login
                check_path:           login
                csrf_token_generator: security.csrf.token_manager
                provider:             bj_db_provider

            logout:
                path:   /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }
